steps:
 - name: 'ubuntu:xenial'
   args: ['echo', '${_VARIABLE1} to this']
   id: 'A'
 - name: 'ubuntu'
   args: ['echo', '${_VARIABLE1} ${_VARIABLE2}']
   id: 'B'
   waitFor: ['-'] 
 - name: 'ubuntu'
   args: ['echo', 'hello $_AB']
   id: 'C'
   waitFor: ['A','B'] 
substitutions:
  _VARIABLE1: welcome
  _VARIABLE2: Kavitha
options:
    substitution_option: 'ALLOW_LOOSE'

