steps:
 - name: 'gcr.io/cloud-builders/javac'
   args: ['Helloworld.java']
   id: 'A'
 - name: 'ubuntu'
   args: ['echo', '${_VARIABLE1} ${_VARIABLE2}']
   id: 'B'
   waitFor: ['-'] 
 - name: 'ubuntu'
   args: ['echo', 'hello $_AB']
   id: 'C'
   waitFor: ['B'] 
substitutions:
  _VARIABLE1: welcome
  _VARIABLE2: Kavitha
artifacts:
  objects:
    location: 'gs://artifact_bucket/'
    paths: ['HelloWorld.class'] 
options:
    substitution_option: 'ALLOW_LOOSE'

